export const GET_ROOM_SOCKET = 'GET_ROOM'
export const GET_ROOMS_SOCKET = 'GET_ROOMS'
export const GET_USER_ROOMS_SOCKET = 'GET_USER_ROOMS'

export const CREATE_ROOM_SOCKET = 'CREATE'
export const CREATE_ERROR_SOCKET = 'CREATE_ERROR'
export const CREATE_SUCCESS_SOCKET = 'CREATE_SUCCESS'

export const JOIN_ROOM_SOCKET = 'JOIN'
export const JOIN_ROOM_SUCCESS_SOCKET = 'JOIN_SUCCESS'
export const JOIN_ROOM_ERROR_SOCKET = 'JOIN_ERROR'
export const JOIN_ACCESS_SOCKET = 'JOIN_ACCESS'

export const DELETE_USER_ROOM_SOCKET = 'DELETE_USER_ROOM'
export const DELETE_USER_ROOM_ERROR_SOCKET = 'DELETE_USER_ROOM_ERROR'
export const DELETE_USER_ROOM_SUCCESS_SOCKET = 'DELETE_USER_ROOM_SUCCESS'

export const UPDATE_USER_ROOM_SOCKET = 'UPDATE_USER_ROOM'
export const UPDATE_USER_ROOM_SUCCESS_SOCKET = 'UPDATE_USER_ROOM_SUCCESS'
export const UPDATE_USER_ROOM_ERROR_SOCKET = 'UPDATE_USER_ROOM_ERROR'

export const GET_CHAT_SOCKET = 'GET_CHAT'
export const CHAT_MESSAGE_SOCKET = 'CHAT_MESSAGE'
export const CHAT_ERROR_SOCKET = 'CHAT_ERROR'

export const CONNECTION_DRAW_SOCKET = 'CONNECTION_DRAW'
export const FINISH_DRAW_SOCKET = 'FINISH_DRAW'
export const CASE_EXIT_SOCKET = 'CASE_EXIT'
export const DRAW_SOCKET = 'DRAW'

export const EXIT_SOCKET = 'EXIT'
export const ERROR_SOCKET = 'ERROR'
