export const DEFAULT_HOST_URL = 'http://localhost:5000'
export const DRAW_ONLINE_URL = '/draw_online'
export const HOME_URL = '/'
export const NOT_FOUND_URL = '/not-found'
export const CHECK_ROOM_PASSWORD_URL = '/checkRoompassword'
export const CABINET_URL = '/cabinet'
